var ATTACKER =
{
	ATTACK;
	WEAPON_DAMAGE;
	WEAPON_ARMOUR_PENERATRATION;
	ARMOUR_PENERATRATION_ATTACK;
};
var DEFENDER =
{
	DEFEND
	ARMOUR_COVERAGE
	DEFENDER_RESILIENCE
	DEFENDER_WOUNDS
	ARMOUR_RESILIENCE
};


function hitThing()
{
	var STEP = ((ATTACK + ROLL) - (DEFEND + ROLL));

	if (STEP > 0)
	{
		var COMBINED_COVERAGE = (ARMOUR_COVERAGE - (WEAPON_ARMOUR_PENERATRATION + ARMOUR_PENERATRATION_ATTACK))

		var DAMAGE_STEP = STEP + WEAPON_DAMAGE;

		if (STEP > COMBINED_COVERAGE)
		{
			if (DAMAGE_STEP > DEFENDER_RESILIENCE)
			{
				DEFENDER_WOUNDS++;
			}
			else
			{
				DEFENDER_RESILIENCE - 1
			}
		}
		else
		{
			var COMBINED_RESILIENCE = DEFENDER_RESILIENCE + ARMOUR_RESILIENCE;

			if (DAMAGE_STEP > COMBINED_RESILIENCE)
			{
				DEFENDER_WOUNDS++;
			}
			else
			{
				if (ARMOUR_RESILIENCE > 0)
				{
					ARMOUR_RESILIENCE--;
				}
				else
				{
					DEFENDER_RESILIENCE--;
				}
			}
		}
	}
}