name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install eslint
      run: npm install eslint --global
    - name: Setup default eslint config
      run: npm init @eslint/config
    - name: Run ESLint
      run: eslint . --ext .js,.jsx